<script>(function(){
/*****************************************************************
 * EDITABLE SECTION - CONFIGURE THESE VALUES
 *****************************************************************/
var utmSource="wpmyproject",utmMedium="wpmyproject",newPrice="$55000",newButtonValue="Special Offer",cookieExpiryDays=30,cookieName="ksowpmatch",priceSelectors=["span.price-item--regular","dd[data-cart-item-regular-price]",".price-item.price-item--regular"],buttonSelectors=["input.cart__submit.btn.btn--small-wide","button.checkout"],personalizationData={campaignType:"price_promotion",audienceSegment:"high_value_customers",promotionTier:"premium_discount"};
/*****************************************************************
 *********** MAIN CODE - DO NOT EDIT BELOW THIS LINE *************
 *****************************************************************/
function setCookie(a,b){var c=new Date;c.setTime(c.getTime()+864e5*cookieExpiryDays);var d=JSON.stringify({source:a,medium:b,metadata:personalizationData});document.cookie=cookieName+"="+encodeURIComponent(d)+";expires="+c.toUTCString()+";path=/"}function getCookie(){var a=cookieName+"=",b=document.cookie.split(";");for(var c=0;c<b.length;c++){var d=b[c].trim();if(d.indexOf(a)===0){try{return JSON.parse(decodeURIComponent(d.substring(a.length)))}catch(e){return null}}}return null}function getUTMParams(){var a={},b=window.location.search.substring(1).split("&");for(var c=0;c<b.length;c++){var d=b[c].split("=");if(d.length===2)a[decodeURIComponent(d[0])]=decodeURIComponent(d[1]||"")}return a}function checkUTMMatch(a){var b=a.utm_source&&a.utm_source.toLowerCase()===utmSource.toLowerCase(),c=!utmMedium||(a.utm_medium&&a.utm_medium.toLowerCase()===utmMedium.toLowerCase());if(b&&c){setCookie(a.utm_source,a.utm_medium);return true}var d=getCookie();return!!d&&d.source&&d.source.toLowerCase()===utmSource.toLowerCase()&&(!utmMedium||(d.medium&&d.medium.toLowerCase()===utmMedium.toLowerCase()))}function pushToDataLayer(a,b,c,d){window.dataLayer=window.dataLayer||[];window.dataLayer.push({event:"wp_contentmodify",original_text:a,updated_text:b,field_type:c,element_selector:d,personalization_data:personalizationData,utm_match:{source:utmSource,medium:utmMedium},timestamp:(new Date).toISOString()})}function updateContent(){var a=getUTMParams();if(!checkUTMMatch(a))return false;var b=false;priceSelectors.forEach(function(a){var c=document.querySelectorAll(a);c.forEach(function(d){if(d&&d.textContent&&d.textContent.trim()!==newPrice){var e=d.textContent.trim();d.textContent=newPrice;pushToDataLayer(e,newPrice,"textContent",a);b=true}})});buttonSelectors.forEach(function(a){var c=document.querySelectorAll(a);c.forEach(function(d){if(d&&d.value&&d.value.trim()!==newButtonValue){var e=d.value.trim();d.value=newButtonValue;pushToDataLayer(e,newButtonValue,"valueAttribute",a);b=true}})});return b}function init(){if(updateContent())return;var a=new MutationObserver(function(){if(updateContent())a.disconnect()});a.observe(document.body,{childList:true,subtree:true,characterData:true,attributes:true});setTimeout(updateContent,1e3)}if(document.readyState==="complete"||document.readyState==="interactive")init();else document.addEventListener("DOMContentLoaded",init);
})();</script>
